<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IFrame 1</name>
   <tag></tag>
   <elementGuidId>f9bdcbf7-f2ea-47b2-8c69-178616880fc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.venoframe.vbox-figlio</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>venoframe vbox-figlio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/customer/quick-create-iframe/?iframe=pos&amp;input=customer_id</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;&quot;]/body[@class=&quot;dashboard-3 vbox-open&quot;]/div[@class=&quot;vbox-overlay&quot;]/div[@class=&quot;vbox-container&quot;]/div[@class=&quot;vbox-content&quot;]/iframe[@class=&quot;venoframe vbox-figlio&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/iframe</value>
   </webElementXpaths>
</WebElementEntity>
